---
title: "Untitled"
format: html
---


## Arbeitauftrag und Textsorte

**Arbeitsauftrag** Sie sind Studierender an einer deutschen Universität und wollen neben Ihrem Studium praktische Erfahrung sammeln. Bewerben Sie sich um eine geeignete offene Stelle, z.B. als studentische Hilfskraft oder als PraktikantIn in Ihrem Fachgebiet.

**Textsorte** In Deutschland müssen Sie einer Bewerbung normalerweise ein Bewerbungsschreiben beilegen. Ein Bewerbungsschreiben ist ein Brief, in dem Sie den Adressaten davon überzeugen, dass Sie für die offene Stelle geeignet und die beste Wahl sind. 

Bevor Sie mit dem Schreiben beginnen, nehmen Sie sich die Zeit, einige Beispiele für Bewerbungsschreiben zu lesen und sich mit der Textsorte vertraut zu machen. Nach der Lektüre haben Sie die Möglichkeit, ein eigenes Bewerbungsschreiben zu verfassen. Anschließend sollten Sie Ihren Text überarbeiten und verbessern.


## Lesen: Modelltexte

**Aufgabe** Lesen Sie die folgenden Beispiele für Bewerbungsschreiben einmal schnell durch. Welches Anschreiben passt zu welcher Stellenanzeige?

:::::: {.panel-tabset}

### Anzeige 1 

::: {.text-example .scrollable-text}
**Praktikum im Verlagswesen**

Wir bieten ab sofort ein Praktikum in unserem Buchverlag an. Während des Praktikums erhalten Sie einen Einblick in die Arbeitsabläufe eines Verlags und sammeln praktische Erfahrungen im Umgang mit Sprache und Texten.

Sie sollten Deutschkenntnisse auf B1-Niveau haben und Freude am Umgang mit Sprache und Literatur mitbringen. Eine gewissenhafte und sorgfältige Arbeitsweise ist für uns selbstverständlich.
Wenn Sie flexibel einsetzbar sind und Interesse an einem Praktikum in unserem Buchverlag haben, dann bewerben Sie sich jetzt. Wir freuen uns auf Ihre Bewerbung.
:::

### Anzeige 2

::: {.text-example .scrollable-text}
**Tutor/in für Grundkurs Programmieren gesucht!**

Wir suchen eine/n fortgeschrittene/n Informatikstudent/in mit Erfahrung in der individuellen Betreuung von Studierenden im ersten Studienjahr im Grundkurs Programmieren. Eine zuverlässige und sorgfältige Arbeitsweise sowie praktische Programmiererfahrung werden erwartet. Eine offene und freundliche Persönlichkeit sowie überdurchschnittliche Kenntnisse der Inhalte des Grundkurses sind wünschenswert. Die Arbeitszeit beträgt 20 Stunden/Monat und wird mit 20 Euro brutto pro Stunde vergütet.
:::

### Anschreiben A

::: {.text-example .scrollable-text}

::: {.columns}
::: {.column width=50%}
Verlag für seriöse Literatur    
Abteilung Lektorat  
Zentrale Straße 55  
999666 Großstadt  
:::
::: {.column width=50%}
::: text-right
Mina Merle  
Hauptstraße 9  
666999 Kleinstadt  
Tel.: 0162 93 45 67 123
:::
:::
:::

::: text-right
**08.05.2023, Kleinstadt**
:::

**Bewerbung um ein Praktikum**

Sehr geehrte Damen und Herren,

ich habe auf Ihrer Webseite die Ausschreibung für ein Praktikum in Ihrem Buchverlag gefunden und bewerbe mich hiermit um diese Stelle. Ich studiere Deutsch an der Universität Paderborn und möchte gerne praktische Erfahrungen im Verlagswesen sammeln. Ein Praktikum in Ihrem traditionsreichen Haus wäre eine großartige Bereicherung meines Studiums.

Während meines Studiums habe ich mich intensiv mit Literatur und Sprache auseinandergesetzt, was mein Interesse an der Arbeit in mit Medien und Literatur geweckt hat. Ich habe auch einen Kurs zum Thema Verlagswesen besucht, der mir einen Einblick in die Arbeitsabläufe eines Verlags verschafft hat. Diese Erfahrungen möchte ich gerne in einem Praktikum bei Ihnen vertiefen und ausbauen. Mein Ziel ist es, nach dem Studium eine Anstellung in einem Verlag zu finden und dort meine Leidenschaft für Bücher und das Arbeiten mit Texten auszuleben.

Ich verfüge über gute Deutschkenntnisse und habe Freude am Umgang mit Sprache und Texten. Ich arbeite sorgfältig und gewissenhaft und bin flexibel einsetzbar.

Ich würde mich sehr freuen, wenn Sie mir die Möglichkeit geben würden, meine Kenntnisse im Rahmen eines Praktikums in Ihrem Buchverlag zu vertiefen und zu erweitern, um mich so auf eine zukünftige Karriere im Verlagswesen vorzubereiten. 

Über eine Rückmeldung würde ich mich sehr freuen.

Mit freundlichen Grüßen

Mina Merle
:::

### Anschreiben B

::: {.text-example .scrollable-text}
::: {.columns}
::: {.column width=50%}
Institut für Information  
Lehrstuhl Prof.in Meier
:::

::: {.column width=50%}
::: text-right
Benjamin von Barre  
Nebenstraße 11    
999666 Großstadt  
Tel.: 0185 77 89 34 555
:::
:::
:::

::: text-right
**08.05.2023, Großstadt**
:::

**Bewerbung als Tutor für Programmieren**

Sehr geehrte Damen und Herren,

mit großem Interesse habe ich die Stellenausschreibung für eine Tutorin / einen Tutor im Kurs Programmieren für Bachelorstudierende im ersten Semester an Ihrem renommierten Institut gelesen. Aufgrund meiner fundierten Kenntnisse im Bereich Informatik sowie meiner Erfahrung in der Vermittlung von Lehrinhalten bin ich überzeugt, einen wertvollen Beitrag zu Ihrem Team leisten zu können. 

Als begeisterter Programmierer und fortgeschrittener Informatikstudent an Ihrem Institut verfüge ich nicht nur über das nötige Wissen, sondern auch über die Fähigkeit, dieses Wissen verständlich und strukturiert an Studierende weiterzugeben. Durch meine vorherige Erfahrung als Tutorin konnte ich bereits mein Talent für die individuelle Unterstützung von Studierenden unter Beweis stellen. Den Grundkurs Programmieren habe ich selbst mit Bestnote abgeschlossen.

Mein zuverlässiger und sorgfältiger Arbeitsstil ermöglicht es mir, mich vollständig auf die Bedürfnisse der Studierenden zu konzentrieren. Dabei versuche ich immer, durch eine offene und freundliche Arbeitsatmosphäre das Lernen zu erleichtern und die Studierenden zu motivieren.

Mein Ziel ist es, den Studierenden nicht nur das nötige Wissen im Kurs Programmieren zu vermitteln, sondern sie auch zu inspirieren und ihre Begeisterung für die Informatik zu wecken. Aufgrund meiner starken Motivation und Leidenschaft für die Informatik möchte ich zukünftig als Dozentin an der Universität arbeiten und Informatik unterrichten.

Gerne stehe ich Ihnen für weitere Fragen zur Verfügung. Ich freue mich auf die Chance, als Tutorin im Kurs Programmieren tätig zu sein und so zur hohen Qualität der Lehre an Ihrem Institut beizutragen.

Mit freundlichen Grüßen

Benjamin Barre
:::

::::::

## Lesen: Textmuster *Bewerbungsschreiben*

**Aufgabe** Lesen Sie die Bewerbungsschreiben noch einmal genauer. Markieren Sie die Antworten auf folgende Fragen:

(1) Wie hat der/die BewerberIn von der offenen Stelle erfahren?
(2) Wieso bewirbt sich der/die BewerberIn?
(3) Welche Qualifikationen und Fähigkeiten bringt der/die BewerberIn mit?
(4) Welche eigenen Ziele oder Zukunftspläne hat der/die BewerberIn?

**Aufgabe** Wo finden Sie folgende Bestandteile? Markieren Sie im Text.

* Anrede
* Verabschiedung
* Kontaktdaten

## Lesen: Nützliche Formulierungen

**Aufgabe** Markieren Sie in den Texten diejenigen Formulierungen, mit denen die Bewerber 

* ihr Interesse an der Stelle ausdrücken.
* ihre eigenen Qualitäten betonen.
* ihre Ziele benennen.
* dem Empfänger schmeicheln.

## Schreiben: Ausschreibung genau lesen

**Aufgabe** Suchen Sie eine offene Stellenausschreibung online. Lesen Sie die Ausschreibung genau und notieren Sie das gesuchte Profil, d.h. die erwarteten Tätigkeiten und die gewünschten Qualifikationen. Alternativ: Lesen Sie die HSK-Ausschreibung genau durch und notieren Sie, was von Bewerbern erwartet wird und welche Ziele das Programm verfolgt.

**Aufgabe** Notiere Sie stichpunktartig Ihre Antworten: Was in Ihrer Biographie und Ihrem Profil passt auf die Ausschreibung?

## Schreiben: Ordnen und formulieren

**Aufgabe** Ordnen Sie jetzt Ihre Argumente und ergänzen Sie, was Ihnen noch einfällt. Die folgenden Leitfragen helfen Ihnen. 

::: {.text-example style="overflow-y: none; max-height: 700px"}

<br>

*Wie haben Sie von der offenen Stelle / dem HSK-Stipendium erfahren?*

<br>

*Wieso bewerben Sie sich?*

<br>

*Wieso sind Sie geeignet? (Ihre Fähigkeiten und Qualifikationen)*

<br>

*Welche relevanten Erfahrungen und Eigenschaften bringen Sie mit? (Ihre Erfahrungen, Ihr Charakter)*

<br>

*Welche Zukunftspläne haben Sie? Was motiviert Sie?*

<br>

:::

**Aufgabe** Formulieren Sie jetzt Ihr Bewerbungsschreiben. Achten Sie auf die Übergänge zwischen den einzelnen Teilen. Vergessen Sie nicht, eine freundliche Anrede und eine geeignete Verabschiedung zu ergänzen. Schmeicheln Sie dem Empfänger ein bisschen, um ihn freundlich zu stimmen.

## Überarbeiten

**Aufgabe** Tauschen Sie Ihre Text mit einem Kommilitonen aus. Lesen Sie den Text Ihres Kommilitonen und geben Sie Feedback:

- Hat der Text die richtige Länge?
- Ist der Text verständlich?
- Sind alle wichtigen Informationen (Fähigkeiten, Erfahrungen, Motivation) enthalten?
- Ist der Text stilistisch gelungen?

**Aufgabe** Lassen Sie Ihren Text von der KI [*DeepL Write*](https://www.deepl.com/write) überprüfen.